project:
  type: website
  output-dir: _site
  render:
    - index.qmd
website:
  title: "Was Trump to Blame for the January 6 Capitol Attacks? Republicans Couldn't Decide."

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    number-sections: true

execute:
  freeze: auto