project:
  type: website
  output-dir: _site

website:
  title: "My Research Paper"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    number-sections: true

execute:
  freeze: auto