project:
  type: website
  output-dir: _site
  render:
    - index.qmd
website:
  title: "Right-wing media split GOP loyalties after January 6"

format:
  html:
    theme: journal
    toc: true
    code-fold: true
    number-sections: true

execute:
  freeze: auto